### ISSUE TITLE
Add the notion of Configuration files.

### ISSUE THREAD

**Issue by marclop** [marclop/elasticsearch-cli#6]
## Summary
Right now configuring `elasticsearch-cli` is not much fun if you're always connecting to the same cluster:

```
elasticsearch-cli -host https://cluster-id.us-east-1.aws.found.io:9243 -user <USER> -pass <PASS>
```

It would be a really good step forward to have the notion of configuration files in `elasticsearch-cli` so that you could choose your _usual_ clusters more easily

## Example

Having a configuration file, specifying all the connection / configuration details

```yaml
clusters:
  - my_usual_cluster:
    url: https://cluster-id.us-east-1.aws.found.io:9243
    user: USER
    pass: PASS
```

```
elasticsearch-cli -cluster my_usual_cluster
```
